FROM debian:latest

WORKDIR /tmp/

RUN apt-get update
RUN apt-get install -y python3 python3-pip rtl-433 libpq-dev procps

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
COPY . /opt/app

CMD ["python3", "/opt/app/handler.py"]
